language: cpp
compiler: gcc

sudo: required
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - fonts-droid
    - libsdl2-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-date-time-dev
    - libfreeimage-dev
    - libcurl4-openssl-dev
    - libasound2-dev
    - libgl1-mesa-dev
    - libvlc-dev
    - libvlccore-dev
    - vlc-nox
env:
- MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
    - eval "${MATRIX_EVAL}"

script:
- cmake .
- make
