language: cpp
compiler: gcc

sudo: required
dist: trusty

addons:
  apt:
    packages:
    - fonts-droid
    - libsdl2-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-date-time-dev
    - libboost-locale-dev
    - libfreeimage-dev
    - libcurl4-openssl-dev
    - libasound2-dev
    - libgl1-mesa-dev

script:
- cmake .
- make
