language: cpp
compiler: gcc

sudo: required
dist: trusty

before_install:
  # C++11
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++11
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

addons:
  apt:
    sources:
    - fonts-droid
    - libsdl2-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-date-time-dev
    - libfreeimage-dev
    - libcurl4-openssl-dev
    - libasound2-dev
    - libgl1-mesa-dev
    - libvlc-dev
    - libvlccore-dev
    - vlc-nox

script:
- cmake .
- make
