language: cpp
script:
- cmake .
- make
compiler: gcc
before_install:
- sudo apt-get install libsdl2-dev libboost-system-dev libboost-filesystem-dev libboost-date-time-dev libboost-locale-dev libfreeimage-dev libfreetype6-dev libcurl4-openssl-dev libasound2-dev libgl1-mesa-dev build-essential fonts-droid libvlc-dev libvlccore-dev vlc-nox
