language: cpp
compiler: gcc

sudo: required
dist: precise

before_script:
  - if [[ $TRAVIS_OS_NAME == linux ]]; then
      sudo apt-get -qq update &&
      sudo apt-get install -y
        fonts-droid
        libsdl2-dev
        libboost-system-dev
        libboost-filesystem-dev
        libboost-date-time-dev
        libboost-locale-dev
        libfreeimage-dev
        libeigen3-dev
        libcurl4-openssl-dev
        libasound2-dev
        libgl1-mesa-dev
    ; fi
script:
- cmake .
- make
